services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lumi-backend
    ports:
      - "8888:8888"
    environment:
      - DEVELOPMENT=false
    networks:
      - lumi-network
    healthcheck:
      test: ["CMD", "/usr/local/bin/lumi-api", "--health-check"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lumi-frontend
    ports:
      - "3000:8080"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - lumi-network
    restart: unless-stopped

networks:
  lumi-network:
    driver: bridge
